---
- hosts: local
  become: yes
  tasks:
    - name: Check if Grafana is already installed
      command: grafana-server --version
      register: grafana_check
      ignore_errors: yes

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      when: grafana_check.rc != 0

    - name: Add Grafana repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
      when: grafana_check.rc != 0

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes
      when: grafana_check.rc != 0

    # Add config and systemd service tasks as needed