---
- hosts: local
  become: yes
  tasks:
    - name: Check if Loki is already installed
      command: loki --version
      register: loki_check
      ignore_errors: yes

    - name: Download Loki
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.9.7/loki-linux-amd64.zip
        dest: /tmp/loki.zip
      when: loki_check.rc != 0

    - name: Unzip Loki
      unarchive:
        src: /tmp/loki.zip
        dest: /usr/local/bin/
        remote_src: yes
      when: loki_check.rc != 0

    - name: Make Loki executable
      file:
        path: /usr/local/bin/loki-linux-amd64
        mode: '0755'
        state: file
      when: loki_check.rc != 0

    - name: Symlink Loki binary
      file:
        src: /usr/local/bin/loki-linux-amd64
        dest: /usr/local/bin/loki
        state: link
      when: loki_check.rc != 0

    # Add config and systemd service tasks as needed