---
- hosts: local
  become: yes
  tasks:
    - name: Check if Prometheus is already installed
      command: prometheus --version
      register: prometheus_check
      ignore_errors: yes

    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz
      when: prometheus_check.rc != 0

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes
      when: prometheus_check.rc != 0

    - name: Symlink Prometheus binary
      file:
        src: /opt/prometheus-2.52.0.linux-amd64/prometheus
        dest: /usr/local/bin/prometheus
        state: link
      when: prometheus_check.rc != 0

    - name: Symlink Promtool binary
      file:
        src: /opt/prometheus-2.52.0.linux-amd64/promtool
        dest: /usr/local/bin/promtool
        state: link
      when: prometheus_check.rc != 0

    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /sbin/nologin
        system: yes
      when: prometheus_check.rc != 0

    # You can add more tasks for config and systemd service here