apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: fastapi-metrics
spec:
  replicas: {{ .Values.fastApiMetrics.replicas }}
  selector:
    matchLabels:
      app: fastapi-metrics
  template:
    metadata:
      labels:
        app: fastapi-metrics
    spec:
      containers:
      - name: fastapi-metrics
        image: {{ .Values.fastApiMetrics.image }}
        ports:
        - containerPort: 8000
          name: http-app
        - containerPort: 8001
          name: http-metrics
        env:
        - name: METRICS_PORT
          value: "8001"
        - name: APP_PORT
          value: "8000"
        - name: LOG_LEVEL
          value: {{ .Values.fastApiMetrics.logLevel | quote }}
        resources:
          limits:
            cpu: {{ .Values.fastApiMetrics.resources.limits.cpu }}
            memory: {{ .Values.fastApiMetrics.resources.limits.memory }}
          requests:
            cpu: {{ .Values.fastApiMetrics.resources.requests.cpu }}
            memory: {{ .Values.fastApiMetrics.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: fastapi-config
          mountPath: /app/config
      volumes:
      - name: fastapi-config
        configMap:
          name: fastapi-metrics-config