apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: kube-state-metrics
spec:
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
  - name: http-metrics
    port: {{ .Values.kubeStateMetrics.service.port }}
    targetPort: 8080
    protocol: TCP
  - name: telemetry
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: kube-state-metrics