apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: {{ .Values.nodeExporter.image }}
        ports:
        - containerPort: 9100
          name: http
        resources:
          limits:
            cpu: {{ .Values.nodeExporter.resources.limits.cpu }}
            memory: {{ .Values.nodeExporter.resources.limits.memory }}
          requests:
            cpu: {{ .Values.nodeExporter.resources.requests.cpu }}
            memory: {{ .Values.nodeExporter.resources.requests.memory }}