apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-exporter
spec:
  type: {{ .Values.postgresExporter.service.type }}
  ports:
  - name: http-metrics
    port: {{ .Values.postgresExporter.service.port }}
    targetPort: 9187
    protocol: TCP
  selector:
    app: postgres-exporter