apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-exporter
spec:
  replicas: {{ .Values.postgresExporter.replicas }}
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: {{ .Values.postgresExporter.image }}
        ports:
        - containerPort: 9187
          name: http-metrics
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-exporter-secret
              key: data-source-name
        resources:
          limits:
            cpu: {{ .Values.postgresExporter.resources.limits.cpu }}
            memory: {{ .Values.postgresExporter.resources.limits.memory }}
          requests:
            cpu: {{ .Values.postgresExporter.resources.requests.cpu }}
            memory: {{ .Values.postgresExporter.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /
            port: 9187
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9187
          initialDelaySeconds: 30
          timeoutSeconds: 10