apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: {{ .Values.namespace }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
    
    positions:
      filename: /tmp/positions/positions.yaml
    
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/containers/*.log
        pipeline_stages:
          - regex:
              expression: '^/var/log/containers/(?P<pod_name>[a-zA-Z0-9\-]+)_(?P<namespace>[a-zA-Z0-9\-]+)_(?P<container_name>[a-zA-Z0-9\-]+)-(?P<container_id>[a-zA-Z0-9]{64})\.log$'
          - labels:
              pod_name:
              namespace:
              container_name:
              container_id: