#// filepath: /Users/skumark5/Documents/opensource-observability-package/Kubernetes Approach/helm-kube-observability-stack/templates/promtail-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
      - name: promtail
        image: {{ .Values.promtail.image }}
        ports:
        - containerPort: 9080
          name: http
        resources:
          limits:
            cpu: {{ .Values.promtail.resources.limits.cpu }}
            memory: {{ .Values.promtail.resources.limits.memory }}
          requests:
            cpu: {{ .Values.promtail.resources.requests.cpu }}
            memory: {{ .Values.promtail.resources.requests.memory }}
        args:
        - -config.file=/etc/promtail/promtail-config.yaml
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config