apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: redis-exporter
spec:
  type: {{ .Values.redisExporter.service.type }}
  ports:
  - name: http-metrics
    port: {{ .Values.redisExporter.service.port }}
    targetPort: 9121
    protocol: TCP
  selector:
    app: redis-exporter