apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: redis-exporter
spec:
  replicas: {{ .Values.redisExporter.replicas }}
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: {{ .Values.redisExporter.image }}
        ports:
        - containerPort: 9121
          name: http-metrics
        env:
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: redis-exporter-secret
              key: redis-addr
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-exporter-secret
              key: redis-password
              optional: true
        args:
        - --redis.addr=$(REDIS_ADDR)
        - --redis.password=$(REDIS_PASSWORD)
        - --web.listen-address=0.0.0.0:9121
        - --web.telemetry-path=/metrics
        - --log-format=txt
        - --debug
        resources:
          limits:
            cpu: {{ .Values.redisExporter.resources.limits.cpu }}
            memory: {{ .Values.redisExporter.resources.limits.memory }}
          requests:
            cpu: {{ .Values.redisExporter.resources.requests.cpu }}
            memory: {{ .Values.redisExporter.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          timeoutSeconds: 10