apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  redis-addr: {{ .Values.redisExporter.redisAddr | b64enc | quote }}
  redis-password: {{ .Values.redisExporter.redisPassword | default "" | b64enc | quote }}