apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: kube-observability-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.7
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-data
          mountPath: /loki
      volumes:
      - name: loki-data
        persistentVolumeClaim:
          claimName: loki-pvc